# cMotion abstracts for questions_text.tcl
#Copied to ASL plugin 
cMotion_abstract_register "locations"
cMotion_abstract_batchadd "locations" { 
  "England" 
  "US" 
  "california" 
  "indiana" 
  "the moon" 
  "australia" 
  "holland" 
  "norway" 
  "boston" 
  "russia" 
  "canada" 
  "toronto" 
  "amsterdam" 
  "mars" 
  "los angeles" 
  "london" 
  "new york" 
  "chicago" 
  "mordor" 
  "middle earth" 
  "the heart of the world" 
}
cMotion_abstract_register "answerWhats"
cMotion_abstract_batchadd "answerWhats" {
  "a book"
  "3 fingers"
  "cycling"
  "I can't tell you that!"
  "a joint"
  "coffee!"
  "pizza"
  "french fries of course!"
  "talking"
  "a TV"
  "nothing%|/looks shifty."
  "some string"
  "a floppy disk"
  "warm"
  "cold"
  "a CD"
  "an mp3"
  "a monitor"
  "a snowboard"
  "a wall"
  "a processor"
  "some cheese"
  "rainbows"
  "kittens"
}
cMotion_abstract_register "answerWheres"
cMotion_abstract_batchadd "answerWheres" {
  "in bed"
  "behind the fridge"
  "on the desk"
  "in a book"
  "California"
  "Amsterdam"
  "a cheese shop"
  "New York"
  "South America"
  "Mars"
  "the USS Enterprise"
  "north pole"
  "in a field"
  "under a book"
  "on top of the telly"
  "in the toilet"
  "Chicago"
  "London"
  "Kansas"
  "%OWNER{%ruser}s house"
  "hidden."
  "in the coffee pot"
  "down the local shop"
  "in the car"
  "at the mall"
  "over thar%|*point*"
  "next to %ruser"
}
cMotion_abstract_register "answerWhens"
cMotion_abstract_batchadd "answerWhens" {
  "this morning"
  "this afternoon"
  "now!"
  "this evening"
  "yesterday"
  "tomorrow"
  "today"
  "in 10 minutes"
  "4:20"
  "7:53"
  "9:21"
  "16:08"
}
cMotion_abstract_register "answerWithWhos"
cMotion_abstract_batchadd "answerWithWhos" {
  "%ruser"
  "me"
  "you"
  "Dan Savage"
  "Jon Stewart"
  "Obama"
  "anyone, i'm easy"
  "at least 3 females"
  "everyone!"
  "at least three men"
  "Beyonce"
  "PSY"
  "Neil DeGrasse Tyson"
}
cMotion_abstract_register "answerWhos"
cMotion_abstract_batchadd "answerWhos" {
  "%ruser"
  "me"
  "you"
  "Dan Savage"
  "Jon Stewart"
  "Obama"
  "anyone, i'm easy"
  "at least 3 females"
  "everyone!"
  "at least three men"
  "Beyonce"
  "PSY"
  "Neil DeGrasse Tyson"
}
cMotion_abstract_register "answerWhys"
cMotion_abstract_batchadd "answerWhys" {
  "why not?"
  "hmm?"
  "because i said so"
  "don't look at me, i thought YOU were responsible for that"
  "sunspots"
  "aliens"
  "too hot"
  "i think %ruser knows..."
  "beats working"
  "entropy"
}
cMotion_abstract_register "answerHowmanys"
cMotion_abstract_batchadd "answerHowmanys" {
  "42"
  "5"
  "34975"
  "ninety-five"
  "minus 6"
  "6"
  "342"
  "pi"
  "0"
  "none"
  "22"
  "%NUMBER{1000}"
}
cMotion_abstract_register "answerHows"
cMotion_abstract_batchadd "answerHows" {
  "magic"
  "pull harder"
  "give it a push"
  "climb on top and try again"
  "using the power of greyskull"
  "try twisting"
  "teamwork"
  "drugs. Gotta be drugs."
  "drop an anvil on it"
  "industrial light and magic"
  "drink red bull first, then try"
}

cMotion_abstract_register "answerWhathaves"
cMotion_abstract_batchadd "answerWhathaves" {
  "%VAR{sillyThings}"
}
cMotion_abstract_register "answerHaveyous"
cMotion_abstract_batchadd "answerHaveyous" {
   "yeah on my %VAR{bodypart}"
   "just this minute actually"
   "we don't like to talk about that anymore %VAR{rarrs}"
   "i can't remember"
   "hell yeah"
   "omg yes"
   "%VAR{lols} %VAR{yesnos}!"
}
cMotion_abstract_register "answerDidyous"
cMotion_abstract_batchadd "answerDidyous" {
  "yeah %VAR{smiles}"
  "yes and i'm gonna do it again %VAR{answerWhens} %VAR{answerWheres}"
  "yeah %VAR{oops} %VAR{smiles}"
}
cMotion_abstract_register "answerWillyous"
cMotion_abstract_batchadd "answerWillyous" {
   "of course!"
   "hand me %VAR{sillyThings} and i'll give it a try :D"
   "can't wait"
   "okie dokie"
   "omg yes"
   "can %ruser watch?"
   "ok but you have to hold my %VAR{bodypart}"
   "no. okay yes."
   "nah"
   "let me think about it. no."
}
cMotion_abstract_register "answerWouldyous"
cMotion_abstract_batchadd "answerWouldyous" {
   "i'd do anything"
   "in a flash!"
   "love to"
   "only if %ruser can watch"
   "would I? I invented the method!"
   "sure, second tuesday of next week."
}

cMotion_abstract_register "answerCanyous"
cMotion_abstract_batchadd "answerCanyous" {
   "certainly"
   "never!"
   "sure"
   "i'd love to! :)"
   "just show me where to sign %VAR{rarrs}"
   "yeah no prob boss"
   "uhm, do I have to?"
   "only if I must"
   "not a chance!"
}
cMotion_abstract_register "answerDoyous"
cMotion_abstract_batchadd "answerDoyous" {
  "normally"
  "always %VAR{rarrs}"
  "i do%|despite having no %VAR{bodypart}"
  "does it mean i get pie?"
  "yahyahayayahayahahayh%colen"
  "indeed i do"
  "omg yes"
  "any chance i get %VAR{rarrs}"
}
cMotion_abstract_register "answerIsyours"
cMotion_abstract_batchadd "answerIsyours" {
  "omg yes"
  "yes!"
}
cMotion_abstract_register "answerWhatOdds"
cMotion_abstract_batchadd "answerWhatOdds" {
  "one in a million"
  "one to %NUMBER{10000}"
  "%NUMBER{10000} to one"
  "... one to something really, really big?"
  "about a snowball's chance in hell"
  "that depends. is %ruser involved?"
  "that depends entirely on %VAR{sillyThings}"
}

cMotion_abstract_register "answerHowLongs"
cMotion_abstract_batchadd "answerHowLongs" {
  "%NUMBER{60} minutes"
  "%NUMBER{60} seconds"
  "%NUMBER{365} days"
  "%NUMBER{1000} years"
  "all your life"
  "all my life"
  "as long as I can hold my breath"
  "until something explodes"
  "six to eight weeks, usually"
}

cMotion_abstract_register "answerHowOlds"
cMotion_abstract_batchadd "answerHowOlds" {
  "%NUMBER{60} minutes"
  "%NUMBER{60} seconds"
  "%NUMBER{365} days"
  "%NUMBER{100} years"
  "about as old as %ruser"
  "about as old as %VAR{sillyThings}"
  "older than %ruser"
  "older than %VAR{sillyThings}"
  "too old"
  "too young"
  "old enough"
  "%VAR{answerHowmanys}"
  "%VAR{answerHowLongs}"
}

cMotion_abstract_register "answerHowBigs"
cMotion_abstract_batchadd "answerHowBigs" {
  "huge"
  "tiny"
  "too big"
  "too small"
  "big enough"
  "small enough"
  "about as big as %ruser"
  "about as small as %ruser"
  "about as big as %VAR{sillyThings}"
  "about as small as %VAR{sillyThings}"
  "%NUMBER{200} inches"
  "%NUMBER{100} metres"
  "%NUMBER{50} miles"
}

cMotion_abstract_register "randomReplies"
cMotion_abstract_batchadd "randomReplies" {
  "%ruser"
  "Orange."
  "about half-past three, I think"
  "more fun than a bucket of chum"
  "more fun than a bucket of %VAR{sillyThings}{strip}"
  "yes"
  "no"
  "maybe"
  "medium-rare"
  "no thanks, i already have some"
  "woah cool, let me try that!"
  "sorry no, I'm still sore from last time"
  "eh?"
  "what?"
  "yellow, and sometimes blue"
  "I like cheddar best of all"
  "perhaps"
  "I didn't like it before"
  "someone set up us the bomb"
  "we get signal"
  "nothing"
  "what do you think?"
  "i can't tell you that"
  "it wasn't me"
  "miami"
  "amsterdam"
  "you should ask jeeves :)"
  "i'd rather not"
  "not particularly, no"
  "last night, yes"
  "i'll consider that"
  "do you really want to know that?"
  "i am not at liberty to discuss that"
  "only with you"
  "why the hell not"
  "only if there are no alternatives"
  "what a silly question *giggle*"
  "let's all ask each other! that'll solve this problem!"
  "only on Wednesdays"
  "42"
  "a tv"
  "shopping"
  "sailing"
  "coffee"
  "lots and lots of tea"
  "french fries of course!"
  "only with you %%"
  "only with %ruser"
  "no."
  "yes."
  "yes, but only on sundays and selected bank holidays"
  "yes, but only on the third wednesday of every month"
  "over there"
  "crap"
  "yes, that makes me horny"
  "yes, but only at the weekend"
  "no, never, not me"
  "you wish"
  "lemmie go look that up"
  "brb - library"
  "i'll need to look that one up %%"
  "i wish i knew"
  "have you tried google?"
  "www.google.com"
  "wtf are you asking me for?"
  "sometimes"
  "perhaps"
  "only with popcorn"
  "only with %ruser"
  "sunday"
  "tuesday"
  "no, but it does make me horny"
  "no, that doesn't make me horny"
  "can i phone a friend?"
  "can i ask the audience?"
  "what do you think this is? Who Wants to be a Millionaire"
  "only when you win the lottery"
  "ask someone else"
  "69"
  "i know, but i have to be paid in pies"
  "if i tell you, i will have to kill you"
  "you want the answer? you can't handle the answer!"
  "you want the truth? you can't handle the truth!"
  "let me consult a fortune cookie"
  "let me check your horoscope"
  "i'm not psychic"
  "omg yes"
  "omg no"
  "i might know"
  "i'll tell ya later"
  "only with fruit"
  "take one little step left"
  "who knows"
  "i might answer, one day"
  "death comes to those who wait"
  "what is your favourite color?"
  "can i check?"
  "i might"
  "one day"
  "green%|No! Blue!"
  "a shrub"
  "a bush"
  "a shrubbery"
  "that depends. Who's asking?"
}
